apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fund-parents-app.fullname" . }}-environment
  labels:
    {{- include "fund-parents-app.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}