version: '3.3'

services:
  postgres:
    image: docker.io/bitnami/postgresql:13
    environment:
      - POSTGRES_USER=fund-parents
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local